default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['ENGLISH_TECH_DATABASE_USERNAME'] %>
  password: <%= ENV['ENGLISH_TECH_DATABASE_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: english_tech_development

test:
  <<: *default
  database: english_tech_test