source "https://rubygems.org"

ruby "3.2.3"

gem "rails", "~> 7.1.3", ">= 7.1.3.4"

gem "sqlite3", "~> 1.4"

gem "puma", ">= 5.0"

gem "tzinfo-data", platforms: %i[ windows jruby ]

gem "rack-cors"

gem "rest-client"

gem "bootsnap", require: false

gem "dotenv-rails"

gem "mysql2", "~> 0.5"

gem "pry-rails"

gem "bcrypt"

gem "jwt"

gem "firebase"

gem "jbuilder"

gem "openai"

gem "ruby-openai"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
end

group :development do

end

